### ISSUE TITLE
Question: install on Mac fails

### ISSUE THREAD

**Issue by weixie4** [lan496/pyzdd#59]
Dear Dr. Shinohara. 

I tried to install pyzdd on my mac but enconter the following. Can you give me some suggestion? Thanks.

Best
Wei

      Traceback (most recent call last):
        File "/Users/weixie/.conda/envs/dsenum/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/Users/weixie/.conda/envs/dsenum/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/weixie/.conda/envs/dsenum/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/weixie/.conda/envs/dsenum/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 60, in <module>
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-build-env-yrv9n0aa/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 56, in build_extension
        File "/Users/weixie/.conda/envs/dsenum/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-install-nb62syjn/pyzdd_be75cc0aa4b54f8ab65703e4ef79045e', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/rx/ct94ynys17z_q8gq875x2vsw0000gn/T/pip-install-nb62syjn/pyzdd_be75cc0aa4b54f8ab65703e4ef79045e/build/lib.macosx-10.9-x86_64-cpython-312/', '-DPYTHON_EXECUTABLE=/Users/weixie/.conda/envs/dsenum/bin/python3.1', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzdd
Failed to build pyzdd
ERROR: Could not build wheels for pyzdd, which is required to install pyproject.toml-based projects

**Comment by lan496** [comment]
Your error messages saild `ModuleNotFoundError: No module named 'cmake'`.
What happens when you install cmake?

**Comment by weixie4** [comment]
Installing cmake (via either conda or pip) resolves the issue. My Mac had already cmake installed via homebrew, but I realized I need to install cmake python package per your suggestion, so that python can can cmake via the cmake module. Thanks Dr. Shinohara!

**Comment by weixie4** [comment]
Installing cmake (via either conda or pip) resolves the issue. My Mac had already cmake installed via homebrew, but I realized I need to install cmake python package per your suggestion, so that python can can cmake via the cmake module. Thanks Dr. Shinohara!
